name: Dependency Audit

on:
  schedule:
    - cron: "0 0 * * 0" # Runs weekly on Sunday
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm audit --audit-level=high
      - name: Upload audit report
        if: always()
        run: |
          mkdir -p audit-report
          npm audit --json > audit-report/npm-audit.json || true
      - name: Upload audit artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: audit-report/
